# Generated by Django 6.0 on 2026-02-03 17:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BankAccount',
            fields=[
                ('account_number', models.BigAutoField(primary_key=True, serialize=False)),
                ('full_name', models.CharField(max_length=100)),
                ('date_of_birth', models.DateField()),
                ('phone_number', models.CharField(max_length=15, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('aadhaar_number', models.CharField(max_length=12, unique=True)),
                ('pan_number', models.CharField(max_length=10, unique=True)),
                ('profile_photo', models.ImageField(blank=True, null=True, upload_to='profile_photos/')),
                ('gender', models.CharField(choices=[('MALE', 'Male'), ('FEMALE', 'Female'), ('OTHER', 'Other')], max_length=10)),
                ('address', models.TextField()),
                ('state', models.CharField(max_length=50)),
                ('account_balance', models.DecimalField(decimal_places=2, default=1000.0, max_digits=12)),
                ('transaction_pin', models.CharField(max_length=128)),
                ('nominee_name', models.CharField(max_length=100)),
                ('nominee_phone', models.CharField(max_length=15)),
                ('nominee_relationship', models.CharField(choices=[('FATHER', 'Father'), ('MOTHER', 'Mother'), ('SPOUSE', 'Spouse'), ('BROTHER', 'Brother'), ('SISTER', 'Sister'), ('OTHER', 'Other')], max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
