# Generated by Django 6.0 on 2026-02-04 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bankaccount',
            name='user',
        ),
        migrations.AlterField(
            model_name='bankaccount',
            name='nominee_phone',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='bankaccount',
            name='transaction_pin',
            field=models.CharField(blank=True, max_length=128),
        ),
    ]
